baseURL = "https://peterponyu.github.io/scCCVGBen/"
languageCode = "en-us"
title = "scCCVGBen — single-cell scCCVGBen Benchmark"
theme = "hugo-book"

[params]
  description = "Multi-encoder, multi-graph, baseline benchmark for scCCVGBen on 200 scRNA+scATAC datasets"
  BookSearch = true
  BookToC = true
  SccFontScaleDefault = "large"
