"""Compose figures/manuscript_figures.pdf from per-figure PNG renderings.

Reads the runtime registry from make_all_figures (single source of truth),
locates each figure's PNG output (preliminary or final), stacks them into a
multi-page PDF using Pillow (no pypdf dep), and writes
figures/manuscript_figures.manifest.json — a serialised snapshot of the
registry's compose-time state. The manifest is regenerated by this composer
and is never hand-edited.
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path

from PIL import Image

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.make_all_figures import REGISTRY  # noqa: E402

log = logging.getLogger(__name__)


def _png_for(figure_glob: str, out_dir: Path) -> list[Path]:
    """Return PNG counterpart paths for a given pdf glob."""
    return sorted(out_dir.glob(figure_glob.replace(".pdf", ".png")))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-dir", type=Path, default=REPO_ROOT / "figures")
    parser.add_argument("--manuscript", type=Path,
                        default=None,
                        help="Output PDF path (defaults to <out-dir>/manuscript_figures.pdf).")
    args = parser.parse_args(argv)

    logging.basicConfig(level=logging.INFO, format="%(message)s")
    out_dir = args.out_dir.resolve()
    if not out_dir.is_dir():
        log.error("out-dir missing: %s", out_dir)
        return 1
    manuscript = (args.manuscript.resolve() if args.manuscript else
                  (out_dir / "manuscript_figures.pdf"))
    manifest_path = out_dir / "manuscript_figures.manifest.json"

    pages: list[Image.Image] = []
    manifest_entries: list[dict] = []
    page_idx = 0

    for spec in REGISTRY:
        pngs = _png_for(spec.output_glob, out_dir)
        if not pngs:
            log.warning("fig %s: no PNG found (glob=%s) — skipped",
                        spec.figure_id, spec.output_glob)
            manifest_entries.append({
                "figure_id": spec.figure_id,
                "page": None,
                "preliminary": True,
                "source": None,
                "missing": True,
            })
            continue
        for png in pngs:
            page_idx += 1
            img = Image.open(png).convert("RGB")
            pages.append(img)
            manifest_entries.append({
                "figure_id": spec.figure_id,
                "page": page_idx,
                "preliminary": ".PRELIMINARY." in png.name,
                "source": png.name,
                "missing": False,
            })

    if not pages:
        log.error("no figure PNGs found in %s", out_dir)
        return 1

    pages[0].save(
        manuscript, save_all=True,
        append_images=pages[1:],
        format="PDF", resolution=150.0,
    )
    log.info("wrote %s (%d page%s)", manuscript, len(pages),
             "" if len(pages) == 1 else "s")

    manifest = {
        "manuscript_pdf": str(manuscript.relative_to(REPO_ROOT)),
        "n_pages": len(pages),
        "any_preliminary": any(e["preliminary"] for e in manifest_entries
                                if not e["missing"]),
        "entries": manifest_entries,
    }
    manifest_path.write_text(json.dumps(manifest, indent=2))
    log.info("wrote %s", manifest_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
