"""Compatibility shim for architecture-only Figure 2 rendering.

The manuscript-facing Figure 2 is generated by
``scripts/make_figure2_composite.py`` as
``figures/fig02_benchmark_architecture.{pdf,png}``. This wrapper keeps the
older architecture-only entrypoint available, but it writes only the panel-D
intermediate consumed by the composite rather than a competing manuscript
``fig02`` stem.

Outputs:
- figures/fig02_architecture.{pdf,png}
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.make_figure2_model_architecture import make_figure  # noqa: E402

log = logging.getLogger(__name__)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-dir", type=Path, default=REPO_ROOT / "figures")
    parser.add_argument("--partial-ok", action="store_true")
    parser.add_argument("--target-n", type=int, default=0)
    args = parser.parse_args(argv)

    logging.basicConfig(level=logging.INFO, format="%(message)s")
    outputs = make_figure(
        args.out_dir,
        site_static=None,
        stem="fig02_architecture",
    )
    for path in outputs:
        log.info("wrote %s", path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
